export type Tool = {
    name: string;
    category: string;
    tags: string[];
    description: string;
    link: string;
    oneLiner?: string;
}

export const TOOLS: Tool[] = [
    // Developers & Coding
    {
        name: "GitHub Copilot",
        category: "Developers",
        tags: ["Paid", "Industry Standard"],
        description: "The world's most widely adopted AI pair programmer. Intelligent code completion and generation.",
        link: "https://github.com/features/copilot",
    },
    {
        name: "Cursor",
        category: "Developers",
        tags: ["Freemium", "Game Changer"],
        description: "An AI-first code editor (VS Code fork) that understands your entire codebase. Highly recommended.",
        link: "https://cursor.sh/",
    },
    {
        name: "Replit",
        category: "Developers",
        tags: ["Cloud", "Beginner Friendly"],
        description: "Instant development environment with AI powers. Build and deploy apps from your browser.",
        link: "https://replit.com/",
    },
    {
        name: "Tabnine",
        category: "Developers",
        tags: ["Privacy Focused", "Enterprise"],
        description: "AI code completion with a strong focus on privacy and enterprise security.",
        link: "https://www.tabnine.com/",
    },
    {
        name: "Amazon Q",
        category: "Developers",
        tags: ["AWS", "Enterprise"],
        description: "Generative AI assistant modernized for AWS development and IT pros.",
        link: "https://aws.amazon.com/q/",
    },
    {
        name: "Aider",
        category: "Developers",
        tags: ["Open Source", "CLI"],
        description: "AI pair programming in your terminal. Edits multiple files at once.",
        link: "https://aider.chat/",
    },
    {
        name: "Supermaven",
        category: "Developers",
        tags: ["Fast", "Huge Context"],
        description: "The fastest copilot with a 1-million token context window.",
        link: "https://supermaven.com/",
    },
    {
        name: "V0 (Vercel)",
        category: "Developers",
        tags: ["Frontend", "React", "Tailwind"],
        description: "Generate UI components from text prompts. Copy-paste ready code.",
        link: "https://v0.dev/",
    },
    {
        name: "Lovable",
        category: "Developers",
        tags: ["No Code", "Full Stack"],
        description: "Build complete full-stack web apps just by chatting.",
        link: "https://lovable.dev/",
    },
    {
        name: "Bolt.new",
        category: "Developers",
        tags: ["Browser Based", "Full Stack"],
        description: "Prompt, run, edit, and deploy full-stack web applications in the browser.",
        link: "https://bolt.new/",
    },
    {
        name: "Supabase",
        category: "Developers",
        tags: ["Database", "Open Source"],
        description: "Firebase alternative with AI vector search support built-in.",
        link: "https://supabase.com/",
    },
    {
        name: "Hugging Face",
        category: "Developers",
        tags: ["Models", "Open Source"],
        description: "The platform where the machine learning community collaborates on models, datasets, and apps.",
        link: "https://huggingface.co/",
    },
    {
        name: "LangChain",
        category: "Developers",
        tags: ["SDK", "Python/JS"],
        description: "The de-facto standard framework for developing applications powered by language models.",
        link: "https://www.langchain.com/",
    },
    {
        name: "CrewAI",
        category: "Developers",
        tags: ["Multi-Agent", "Python"],
        description: "Framework for orchestrating role-playing, autonomous AI agents.",
        link: "https://www.crewai.com/",
    },

    // Automation & Workflow
    {
        name: "n8n",
        category: "Automation",
        tags: ["Low Code", "Self-Hostable"],
        description: "Powerful workflow automation for technical people. Fair-code distribution.",
        link: "https://n8n.io/",
    },
    {
        name: "Zapier",
        category: "Automation",
        tags: ["No Code", "Easy"],
        description: "The easiest way to automate workflows. Connects 6000+ apps.",
        link: "https://zapier.com/",
    },
    {
        name: "Make",
        category: "Automation",
        tags: ["Visual", "Advanced"],
        description: "Visual platform to build and automate complex tasks and workflows.",
        link: "https://www.make.com/",
    },
    {
        name: "Retool",
        category: "Automation",
        tags: ["Low Code", "Enterprise"],
        description: "Build internal tools remarkably fast. Drag and drop UI, write SQL/JS.",
        link: "https://retool.com/",
    },
    {
        name: "Bland AI",
        category: "Automation",
        tags: ["Phone", "Sales"],
        description: "Realistic AI phone calling agents for sales and support.",
        link: "https://www.bland.ai/",
    },
    {
        name: "UiPath",
        category: "Automation",
        tags: ["Enterprise", "Legacy"],
        description: "Robotic Process Automation for large scale enterprise tasks.",
        link: "https://www.uipath.com/",
    },
    {
        name: "Relume",
        category: "Automation",
        tags: ["Figma", "Sitemap"],
        description: "AI-powered website builder and sitemap generator for designers.",
        link: "https://relume.io/",
    },

    // Productivity & Hidden Gems
    {
        name: "Napkin.ai",
        category: "Productivity",
        tags: ["Hidden Gem", "Diagrams"],
        description: "Instantly turn your text into meaningful visuals and storytelling diagrams.",
        link: "https://napkin.ai/",
    },
    {
        name: "Gamma",
        category: "Productivity",
        tags: ["No Design Skills", "Fast"],
        description: "A new medium for presenting ideas. Generate decks, docs, and webpages.",
        link: "https://gamma.app/",
    },
    {
        name: "Eraser",
        category: "Productivity",
        tags: ["Technical", "Diagram-as-Code"],
        description: "Docs and diagrams for engineering teams. Great for architecture.",
        link: "https://eraser.io/",
    },
    {
        name: "Perplexity",
        category: "Productivity",
        tags: ["Research", "Daily Driver"],
        description: "AI answer engine. Replaces traditional search for many users.",
        link: "https://www.perplexity.ai/",
    },
    {
        name: "Arc Search",
        category: "Productivity",
        tags: ["Mobile", "Summary"],
        description: "Innovative 'Browse for Me' feature summarizing web pages.",
        link: "https://arc.net/",
    },
    {
        name: "Goblin Tools",
        category: "Productivity",
        tags: ["Hidden Gem", "Simple"],
        description: "A set of simple, single-task tools (like 'Judge Tone') to help neurodivergent minds.",
        link: "https://goblin.tools/",
    },
    {
        name: "Humata",
        category: "Productivity",
        tags: ["Analysis", "Research"],
        description: "Chat with your files. Upload PDFs and ask questions.",
        link: "https://humata.ai/",
    },
    {
        name: "NotebookLM",
        category: "Productivity",
        tags: ["Google", "Audio Overview"],
        description: "Your personalized AI research assistant. Generates podcasts from your notes.",
        link: "https://notebooklm.google/",
    },
    {
        name: "Excalidraw",
        category: "Productivity",
        tags: ["Drawing", "Open Source"],
        description: "Virtual whiteboard with 'AI-to-diagram' features.",
        link: "https://excalidraw.com/",
    },
    {
        name: "Midjourney",
        category: "Productivity",
        tags: ["Art", "Best Quality"],
        description: "The highest quality AI image generator available. Discord-based.",
        link: "https://www.midjourney.com/",
    },
    {
        name: "Runway",
        category: "Productivity",
        tags: ["Video", "Creative"],
        description: "Advanced video generation (Gen-3 Alpha) for filmmakers and creators.",
        link: "https://runwayml.com/",
    },
    {
        name: "ElevenLabs",
        category: "Productivity",
        tags: ["Audio", "Realistic"],
        description: "The most realistic AI text-to-speech and voice cloning software.",
        link: "https://elevenlabs.io/",
    },
    {
        name: "Descript",
        category: "Productivity",
        tags: ["Editor", "Transcription"],
        description: "Edit video by editing text. Magic for podcasters.",
        link: "https://descript.com/",
    },
    {
        name: "Suno",
        category: "Productivity",
        tags: ["Audio", "Generation"],
        description: "Make a song about anything. AI music generation.",
        link: "https://suno.com/",
    },
    {
        name: "Bolt.diy",
        category: "Developers",
        tags: ["Hidden Gem", "Open Source"],
        description: "Open-source fork of Bolt.new allowing self-hosting and use of personal API keys (BYO-LLM) to avoid subscription fees.",
        link: "https://github.com/stackblitz/bolt.new",
    },
    {
        name: "Windsurf",
        category: "Developers",
        tags: ["Freemium", "Hidden Gem"],
        description: "Agentic IDE by Codeium focusing on 'Flows' that allow deep collaboration between human and AI agents within the editor.",
        link: "https://codeium.com/windsurf",
    },
    {
        name: "Softgen",
        category: "Developers",
        tags: ["Paid", "Hidden Gem"],
        description: "No-code web app builder for non-technical founders. Uses a wholesale pricing model (annual license + at-cost AI credits).",
        link: "https://softgen.ai",
    },
    {
        name: "Base44",
        category: "Developers",
        tags: ["Freemium", "Hidden Gem"],
        description: "Vibe coding platform handling auth, database, and payments (Stripe) out of the box. Focuses on 'Business-in-a-box' generation.",
        link: "https://base44.com",
    },
    {
        name: "Databutton",
        category: "Developers",
        tags: ["Freemium", "Hidden Gem"],
        description: "AI app builder specialized for data applications and Python backends. Integrates well with Streamlit-style logic.",
        link: "https://databutton.com",
    },
    {
        name: "Flux.1",
        category: "Design",
        tags: ["Open Source"],
        description: "State-of-the-art open weights image generation model. Excellent text rendering and prompt adherence.",
        link: "https://blackforestlabs.ai",
    },
    {
        name: "Recraft",
        category: "Design",
        tags: ["Freemium", "Hidden Gem"],
        description: "Generative design tool for Vector (SVG) graphics. Features 'Brand Style' consistency for logos and icons.",
        link: "https://recraft.ai",
    },
    {
        name: "Ideogram",
        category: "Design",
        tags: ["Freemium"],
        description: "Image generator specializing in typography and text integration. 'Canvas' feature allows for infinite design editing.",
        link: "https://ideogram.ai",
    },
    {
        name: "Krea AI",
        category: "Design",
        tags: ["Freemium"],
        description: "Real-time generative art tool with high-end upscaling and enhancing capabilities.",
        link: "https://krea.ai",
    },
    {
        name: "Vectorizer.ai",
        category: "Design",
        tags: ["Paid", "Hidden Gem"],
        description: "Deep learning utility to convert raster images (JPEG/PNG) into full-color geometric vectors (SVG).",
        link: "https://vectorizer.ai",
    },
    {
        name: "Magnific AI",
        category: "Design",
        tags: ["Paid"],
        description: "Premium upscaler that 'hallucinates' details into low-res images, adding texture and realism.",
        link: "https://magnific.ai",
    },
    {
        name: "Kling AI",
        category: "Video",
        tags: ["Image-to-Video", "Complex Motion", "Freemium", "5s/10s generation"],
        description: "High-fidelity video generator rivaling Sora. Excellent at complex motion and 1080p generation.",
        link: "https://klingai.com",
    },
    {
        name: "Luma Dream Machine",
        category: "Video",
        tags: ["Freemium"],
        description: "Fast video generator with 'Keyframe' control for precise start and end points.",
        link: "https://lumalabs.ai",
    },
    {
        name: "Hedra",
        category: "Video",
        tags: ["Freemium", "Hidden Gem"],
        description: "Audio-driven character animation. Creates expressive lip-sync and body movement from a single image and audio file.",
        link: "https://hedra.com",
    },
    {
        name: "Synthesia",
        category: "Video",
        tags: ["AI Avatars", "Multilingual", "Enterprise Compliance", "Paid"],
        description: "AI Avatar platform for enterprise. Generates training and marketing videos with consistent characters in 120+ languages.",
        link: "https://synthesia.io",
    },
    {
        name: "Clay",
        category: "Sales",
        tags: ["Freemium"],
        description: "Data enrichment platform that acts as a 'Spreadsheet API'. Integrates 50+ data providers for waterfall enrichment.",
        link: "https://clay.com",
    },
    {
        name: "Instantly.ai",
        category: "Sales",
        tags: ["Paid"],
        description: "Cold email platform with unlimited warmup and 'Unibox' for managing mass outreach responses.",
        link: "https://instantly.ai",
    },
    {
        name: "Reply.io",
        category: "Sales",
        tags: ["Paid"],
        description: "Multichannel engagement platform (Email, LinkedIn, SMS) with AI agents that handle responses and booking.",
        link: "https://reply.io",
    },
    {
        name: "Smartlead.ai",
        category: "Sales",
        tags: ["Paid"],
        description: "Email infrastructure for high-volume senders and agencies. Features white-labeling and robust API.",
        link: "https://smartlead.ai",
    },
    {
        name: "WorkBeaver",
        category: "Automation",
        tags: ["Paid", "Hidden Gem"],
        description: "Desktop RPA that uses AI to see the screen and automate tasks in legacy software without APIs. Local execution.",
        link: "https://workbeaver.com",
    },
    {
        name: "Marblism",
        category: "Automation",
        tags: ["Paid", "Hidden Gem"],
        description: "Platform that generates SaaS apps populated with 'AI Employees' for specific roles (SEO, Social, etc.).",
        link: "https://marblism.com",
    },
    {
        name: "Sintra",
        category: "Automation",
        tags: ["Paid", "Hidden Gem"],
        description: "AI workforce platform offering pre-packaged bots for admin and support roles with human-in-the-loop approval.",
        link: "https://sintra.ai",
    },
    {
        name: "AutoGPT",
        category: "Automation",
        tags: ["Open Source"],
        description: "Open-source autonomous agent framework. recursively creates tasks to achieve high-level goals.",
        link: "https://agpt.co",
    },
    {
        name: "Perplexity AI",
        category: "Productivity",
        tags: ["Freemium"],
        description: "Answer engine that replaces traditional search with synthesized, cited answers. 'Pro Search' handles multi-step reasoning.",
        link: "https://perplexity.ai",
    },
    {
        name: "Proactor.ai",
        category: "Automation",
        tags: ["Paid", "Hidden Gem"],
        description: "Meeting intelligence that provides real-time advice and creates tasks during the call. Proactive intervention.",
        link: "https://proactor.ai",
    },
    {
        name: "ChatSlide.ai",
        category: "Productivity",
        tags: ["Freemium", "Hidden Gem"],
        description: "Converts documents and prompts into full educational slide decks with AI narration.",
        link: "https://chatslide.ai",
    },
    {
        name: "Metaview",
        category: "Productivity",
        tags: ["Paid"],
        description: "Interview intelligence tool for recruiters. Transcribes calls and generates scorecards and interviewer feedback.",
        link: "https://metaview.ai",
    },
    {
        name: "Gizmo",
        category: "Education",
        tags: ["Freemium", "Hidden Gem"],
        description: "Gamified learning tool using AI to create flashcards and quizzes from notes/PDFs. Uses spaced repetition.",
        link: "https://gizmo.ai",
    },
    {
        name: "Khanmigo",
        category: "Education",
        tags: ["Paid"],
        description: "Socratic AI tutor by Khan Academy. Guides students to answers rather than providing them directly.",
        link: "https://khanmigo.ai",
    },
    {
        name: "BeeDone",
        category: "Productivity",
        tags: ["Freemium", "Hidden Gem"],
        description: "Gamified to-do list app designed for ADHD/Executive Dysfunction. Uses AI to break large tasks into small steps.",
        link: "https://beedone.co",
    },
    {
        name: "MobiLoud",
        category: "Other",
        tags: ["Paid"],
        description: "High-end wrapper service to convert web apps into native mobile apps with App Store approval guarantee.",
        link: "https://mobiloud.com",
    },
    {
        name: "Twinr",
        category: "Other",
        tags: ["Paid", "Hidden Gem"],
        description: "No-code builder to convert websites to apps. Allows injecting CSS/JS to customize the mobile experience.",
        link: "https://twinr.dev",
    },
    {
        name: "Capacitor",
        category: "Developers",
        tags: ["Open Source"],
        description: "Open-source runtime for building Web Native apps. Access native device APIs from standard web code.",
        link: "https://capacitorjs.com",
    },
    {
        name: "Udio",
        category: "Audio",
        tags: ["Freemium"],
        description: "High-fidelity music generator known for vocal clarity and remixing/extending capabilities.",
        link: "https://udio.com",
    },
    {
        name: "Endel",
        category: "Audio",
        tags: ["Freemium"],
        description: "Neuroscience-backed functional soundscapes for focus, sleep, and relaxation. Adapts to weather and heart rate.",
        link: "https://endel.io",
    },
    {
        name: "Murf.ai",
        category: "Audio",
        tags: ["Paid"],
        description: "Studio-quality voiceover platform with timeline editor for precise control over pitch and emphasis.",
        link: "https://murf.ai",
    },
    {
        name: "Superlist",
        category: "Productivity",
        tags: ["Freemium", "Hidden Gem"],
        description: "Design-centric task manager blending notes and to-dos. From the creators of Wunderlist.",
        link: "https://superlist.com",
    },
    {
        name: "Janitor AI",
        category: "Other",
        tags: ["Uncensored", "Freemium", "API Proxy", "Hidden Gem", "Character Cards"],
        description: "Platform for uncensored character roleplay. Popular for creative writing and interactive storytelling.",
        link: "https://janitorai.com",
    },
    {
        name: "Nomi.ai",
        category: "Other",
        tags: ["Companionship", "Freemium", "Hidden Gem", "Long-term Memory", "Emotional IQ"],
        description: "AI companion app focused on long-term memory and emotional intelligence. Characters remember past conversations.",
        link: "https://nomi.ai",
    },
    {
        name: "Raycast",
        category: "Productivity",
        tags: ["Freemium"],
        description: "Mac spotlight replacement with deep AI integration for system-wide commands and snippets.",
        link: "https://raycast.com",
    },
    {
        name: "xTiles",
        category: "Productivity",
        tags: ["Freemium", "Hidden Gem"],
        description: "Visual note-taking tool described as a 'second brain' for visual learners. Combines canvas and document formats.",
        link: "https://xtiles.app",
    },
    {
        name: "SaneBox",
        category: "Productivity",
        tags: ["Paid"],
        description: "AI email management that filters unimportant emails into folders, keeping the inbox clean.",
        link: "https://sanebox.com",
    },
    {
        name: "AppMySite",
        category: "Other",
        tags: ["Paid"],
        description: "No-code app builder optimized for WordPress and WooCommerce sites. Imports content automatically.",
        link: "https://appmysite.com",
    },
    {
        name: "BuildFire",
        category: "Other",
        tags: ["Paid"],
        description: "Modular app builder with a plugin marketplace. Good for businesses needing specific functionality like loyalty programs.",
        link: "https://buildfire.com",
    },
    {
        name: "Woodpecker",
        category: "Sales",
        tags: ["Paid"],
        description: "Cold email tool focusing on agency workflows and deliverability protection. Competitor to Instantly.",
        link: "https://woodpecker.co",
    },
    {
        name: "Apollo.io",
        category: "Sales",
        tags: ["Freemium"],
        description: "Massive B2B database and engagement platform. The industry standard for sourcing leads.",
        link: "https://apollo.io",
    },
    {
        name: "OpusClip",
        category: "Video",
        tags: ["Freemium"],
        description: "AI repurposing tool that takes long videos (podcasts) and cuts them into viral short clips with captions.",
        link: "https://opus.pro",
    },
    {
        name: "Google Veo",
        category: "Video",
        tags: ["Freemium"],
        description: "Google's answer to Sora. High-definition video generation integrated into YouTube Shorts and Workspace.",
        link: "https://deepmind.google/technologies/veo",
    },
    {
        name: "HeyGen",
        category: "Video",
        tags: ["Paid"],
        description: "AI Avatar video generator. Famous for its 'Instant Avatar' feature that clones a user's likeness from a webcam video.",
        link: "https://heygen.com",
    },
    {
        name: "Leonardo.ai",
        category: "Design",
        tags: ["Freemium"],
        description: "Comprehensive AI art platform with fine-tuned models for game assets and textures. Competitor to Midjourney.",
        link: "https://leonardo.ai",
    },
    {
        name: "Canva Magic Studio",
        category: "Design",
        tags: ["Freemium"],
        description: "Suite of AI tools within Canva. Includes Magic Eraser, Magic Edit, and Text-to-Image.",
        link: "https://canva.com",
    },
    {
        name: "CodeMate",
        category: "Developers",
        tags: ["Freemium", "Hidden Gem"],
        description: "AI coding assistant that focuses on auto-debugging and correcting code within VS Code.",
        link: "https://codemate.ai",
    },
    {
        name: "Jasper",
        category: "Sales",
        tags: ["Paid"],
        description: "AI copywriter for enterprise marketing teams. Focuses on brand voice and campaign consistency.",
        link: "https://jasper.ai",
    },
    {
        name: "Copy.ai",
        category: "Sales",
        tags: ["Freemium"],
        description: "AI content generator for marketing. 'Workflows' feature allows for bulk content creation.",
        link: "https://copy.ai",
    },
    {
        name: "FeedHive",
        category: "Sales",
        tags: ["Paid"],
        description: "AI social media management tool. Recycles content and predicts best posting times.",
        link: "https://feedhive.com",
    },
    {
        name: "Predis.ai",
        category: "Sales",
        tags: ["Freemium", "Hidden Gem"],
        description: "Generates social media posts (image + caption + hashtag) from a simple text prompt.",
        link: "https://predis.ai",
    },
    {
        name: "AdCreative.ai",
        category: "Sales",
        tags: ["Paid", "Conversion Focus", "Ad Generation", "Analytics"],
        description: "Generates high-converting ad creatives (banners) focused on performance marketing.",
        link: "https://adcreative.ai",
    },
    {
        name: "Tome",
        category: "Productivity",
        tags: ["Freemium"],
        description: "Storytelling tool for generating pitch decks and narratives. Heavy focus on founders.",
        link: "https://tome.app",
    },
    {
        name: "Beautiful.ai",
        category: "Productivity",
        tags: ["Paid"],
        description: "Presentation software that automatically formats slides as you add content.",
        link: "https://beautiful.ai",
    },
    {
        name: "Otter.ai",
        category: "Productivity",
        tags: ["Freemium"],
        description: "Meeting transcription and summary tool. 'OtterPilot' joins meetings automatically.",
        link: "https://otter.ai",
    },
    {
        name: "Fireflies.ai",
        category: "Productivity",
        tags: ["Freemium"],
        description: "Meeting recorder that integrates with CRMs. Analyzes sentiment and speaker talk time.",
        link: "https://fireflies.ai",
    },
    {
        name: "Fathom",
        category: "Productivity",
        tags: ["Free Unlimited", "Zoom Integration", "Free", "Instant Access"],
        description: "Free meeting recorder for Zoom. instant access to recording and transcript.",
        link: "https://fathom.video",
    },
    {
        name: "Krisp",
        category: "Audio",
        tags: ["Freemium"],
        description: "AI noise cancellation app. Removes background noise and echo from calls in real-time.",
        link: "https://krisp.ai",
    },
    {
        name: "DeepL",
        category: "Other",
        tags: ["Freemium"],
        description: "AI translation tool known for higher nuance and accuracy than Google Translate.",
        link: "https://deepl.com",
    },
    {
        name: "Tableau Pulse",
        category: "Automation",
        tags: ["Paid"],
        description: "AI-powered insights within Tableau. Provides natural language summaries of data trends.",
        link: "https://tableau.com",
    },
    {
        name: "Ajelix",
        category: "Productivity",
        tags: ["Freemium"],
        description: "AI Excel and Google Sheets tools. Generates formulas and VBA scripts from text.",
        link: "https://ajelix.com",
    },
    {
        name: "MonkeyLearn",
        category: "Automation",
        tags: ["Paid"],
        description: "No-code text analytics. Classifies customer feedback and analyzes sentiment.",
        link: "https://monkeylearn.com",
    },
    {
        name: "Flowise",
        category: "Developers",
        tags: ["Visual LangChain", "Hidden Gem", "Open Source", "Chatflows", "No-code LLM"],
        description: "Drag-and-drop UI for LangChain. Allows building LLM apps visually.",
        link: "https://flowiseai.com",
    },
    {
        name: "Brainscape",
        category: "Education",
        tags: ["Freemium"],
        description: "Smart flashcards platform. Uses confidence-based repetition (CBR).",
        link: "https://brainscape.com",
    },
    {
        name: "Gauth Math",
        category: "Education",
        tags: ["Freemium"],
        description: "AI math solver. Scans math problems and provides step-by-step solutions.",
        link: "https://gauthmath.com",
    },
    {
        name: "ClipDrop",
        category: "Design",
        tags: ["Freemium"],
        description: "Suite of visual editing tools acquired by Jasper. Includes background removal, relighting, and upscaling.",
        link: "https://clipdrop.co",
    },
    {
        name: "VidIQ",
        category: "Video",
        tags: ["Freemium"],
        description: "YouTube growth tool with AI features for title generation, keyword research, and video ideas.",
        link: "https://vidiq.com",
    },
    {
        name: "InVideo",
        category: "Video",
        tags: ["Freemium"],
        description: "Text-to-Video editor. Creates video drafts with stock footage and voiceovers from prompts.",
        link: "https://invideo.io",
    },
    {
        name: "Captions.ai",
        category: "Video",
        tags: ["Paid"],
        description: "AI video editing app focused on talking head videos. Adds dynamic captions, eye contact correction, and dubbing.",
        link: "https://captions.ai",
    },
    {
        name: "Mem.ai",
        category: "Productivity",
        tags: ["Freemium"],
        description: "Self-organizing workspace. Uses AI to connect notes and surface relevant information automatically.",
        link: "https://mem.ai",
    },
    {
        name: "Rewind.ai",
        category: "Productivity",
        tags: ["Paid"],
        description: "Records everything you see, say, and hear on your Mac. Allows you to search your past activity.",
        link: "https://rewind.ai",
    },
    {
        name: "Brandwatch",
        category: "Sales",
        tags: ["Paid"],
        description: "Consumer intelligence and social listening platform. Analyzes brand sentiment across the web.",
        link: "https://brandwatch.com",
    },
    {
        name: "BuzzSumo",
        category: "Sales",
        tags: ["Paid"],
        description: "Content research tool. Finds the most shared content for any topic to guide content strategy.",
        link: "https://buzzsumo.com",
    },
    {
        name: "ChatPDF",
        category: "Productivity",
        tags: ["Freemium"],
        description: "Simple tool to chat with PDF files. Upload a PDF and ask questions about it.",
        link: "https://chatpdf.com",
    },
    {
        name: "Clockwise",
        category: "Productivity",
        tags: ["Freemium"],
        description: "AI calendar optimizer. Automatically moves meetings to create blocks of 'Focus Time'.",
        link: "https://getclockwise.com",
    },
    {
        name: "Reclaim.ai",
        category: "Productivity",
        tags: ["Freemium"],
        description: "Smart calendar tool for Google Calendar. Blocks time for habits and tasks automatically.",
        link: "https://reclaim.ai",
    },
    {
        name: "Phind",
        category: "Developers",
        tags: ["Freemium"],
        description: "Search engine optimized for developers. Provides code answers and context from documentation.",
        link: "https://phind.com",
    },
    {
        name: "Looka",
        category: "Design",
        tags: ["Paid"],
        description: "AI logo maker and brand kit generator. Creates logos based on preferences and industry.",
        link: "https://looka.com",
    },
    {
        name: "Lalal.ai",
        category: "Audio",
        tags: ["Paid"],
        description: "Stem splitter. Separates vocals, drums, bass, and instruments from any audio file.",
        link: "https://lalal.ai",
    },
    {
        name: "AudioCipher",
        category: "Audio",
        tags: ["Paid", "Hidden Gem"],
        description: "Melody generator plugin. Converts text prompts into MIDI melodies within DAWs.",
        link: "https://audiocipher.com",
    },
    {
        name: "Mubert",
        category: "Audio",
        tags: ["Freemium"],
        description: "Generative functional music for streamers and apps. Royalty-free background music.",
        link: "https://mubert.com",
    },
    {
        name: "Consensus",
        category: "Productivity",
        tags: ["Freemium"],
        description: "Search engine for scientific research. Answers questions using peer-reviewed papers.",
        link: "https://consensus.app",
    },
    {
        name: "Elicit",
        category: "Productivity",
        tags: ["Freemium"],
        description: "AI research assistant. Automates literature review and finds papers relevant to a query.",
        link: "https://elicit.org",
    },
    {
        name: "Blackbox AI",
        category: "Developers",
        tags: ["Video-to-Code", "Chat", "Freemium", "Autocomplete"],
        description: "Coding assistant that can copy code from videos and images. VS Code extension available.",
        link: "https://blackbox.ai",
    },
    {
        name: "Warp",
        category: "Developers",
        tags: ["Freemium"],
        description: "AI-powered terminal. Modern replacement for the command line with AI command suggestions.",
        link: "https://warp.dev",
    },
    {
        name: "Writesonic",
        category: "Sales",
        tags: ["Freemium"],
        description: "AI writer and chatbot builder. Features 'Audiosonic' for text-to-speech generation.",
        link: "https://writesonic.com",
    },
    {
        name: "Surfer SEO",
        category: "Sales",
        tags: ["Paid"],
        description: "SEO tool that analyzes top-ranking pages and provides content guidelines. Integrated AI writer.",
        link: "https://surferseo.com",
    },
    {
        name: "Rytr",
        category: "Sales",
        tags: ["Freemium"],
        description: "Affordable AI writing assistant. Good for short-form copy and emails.",
        link: "https://rytr.me",
    },
    {
        name: "QuillBot",
        category: "Sales",
        tags: ["Freemium"],
        description: "Paraphrasing tool. Rewrites text to avoid plagiarism or improve flow.",
        link: "https://quillbot.com",
    },
    {
        name: "Notion AI",
        category: "Productivity",
        tags: ["Paid"],
        description: "AI integrated into Notion. Summarizes notes, generates text, and edits content.",
        link: "https://notion.so",
    },
    {
        name: "GrammarlyGO",
        category: "Productivity",
        tags: ["Freemium"],
        description: "Generative AI features within Grammarly. Composes text and replies to emails.",
        link: "https://grammarly.com",
    },
    {
        name: "Shortwave",
        category: "Productivity",
        tags: ["Hidden Gem", "Freemium"],
        description: "AI email client for Gmail. Summarizes threads and drafts replies. Successor to Google Inbox.",
        link: "https://shortwave.com",
    },
    {
        name: "Lavender",
        category: "Sales",
        tags: ["Paid"],
        description: "AI email coach. Grades sales emails and suggests improvements for higher reply rates.",
        link: "https://lavender.ai",
    },
    {
        name: "Gong",
        category: "Sales",
        tags: ["Paid"],
        description: "Revenue intelligence platform. Records calls and analyzes sales conversations for insights.",
        link: "https://gong.io",
    },
    {
        name: "Anyword",
        category: "Sales",
        tags: ["Paid"],
        description: "Performance writing platform. Predicts the performance score of copy before publishing.",
        link: "https://anyword.com",
    },
    {
        name: "Munch",
        category: "Video",
        tags: ["Paid"],
        description: "AI repurposing tool similar to OpusClip. Extracts clips from long-form content.",
        link: "https://getmunch.com",
    },
]
